### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by blegat** [blegat/LowRankOpt.jl#2]
This is just the comment of https://github.com/jump-dev/MathOptInterface.jl/pull/2198 moved here

Note that once this is done, you can write an SDP in [SDPA format](https://jump.dev/MathOptInterface.jl/dev/submodules/FileFormats/reference/#MathOptInterface.FileFormats.SDPA.Model) directly in JuMP with something like
```julia
C = rand(d, d)
A = [rand(d, d) for i in 1:m]
model = Model()
@variable(model, x[1:m+1] in MOI.SetWithDotProducts(
    MOI.PositiveSemidefiniteConeTriangle(d),
    MOI.TriangleVectorization.([A; [C]]),
))
@constraint(model, x[1:m] == b)
@objective(model, Min, x[end])
```
or
```julia
model = Model()
@variable(model, y[1:m])
@constraint(model, [y; -1] in MOI.LinearCombinationInSet([A; [C]]))
@objective(model, Max, dot(y, b))
```
And `Dualization.dualize` should take you from one to the other one!

Solvers implementing this:

- [ ] `Hypatia.LinMatrixIneqCone` : `A1` PSD and `A2, ..., A[m]` arbitrary
- [ ] `Hypatia.WSOSInterpNonnegativeCone` : `A = u u'` (Rank-1 PSD) https://github.com/jump-dev/Hypatia.jl/pull/844
- [ ] `DSDP` : `A = a * u * u'` (Rank-1) https://github.com/jump-dev/DSDP.jl/pull/37
- [x] `SDPLR` : `A = U * Diagonal(d) * U'` (Low-Rank) https://github.com/jump-dev/SDPLR.jl/pull/26

## Basic

 - [x] Add a new `AbstractScalarSet` or `AbstractVectorSet` to `src/sets.jl`
 - [ ] If `isbitstype(S) == false`, implement `Base.copy(set::S)`
 - [ ] If `isbitstype(S) == false`, implement `Base.:(==)(x::S, y::S)`
 - [x] If an `AbstractVectorSet`, implement `dimension(set::S)`, unless the
       dimension is given by `set.dimension`.

## Utilities

 - [x] If an `AbstractVectorSet`, implement `Utilities.set_dot`,
       unless the dot product between two vectors in the set is equivalent to
       `LinearAlgebra.dot`
 - [ ] If an `AbstractVectorSet`, implement `Utilities.set_with_dimension` in
       `src/Utilities/matrix_of_constraints.jl`
 - [x] Add the set to the `@model` macro at the bottom of `src/Utilities.model.jl`

## Documentation

 - [ ] Add a docstring, which gives the mathematical definition of the set,
       along with an `## Example` block containing a `jldoctest`
 - [x] Add the docstring to `docs/src/reference/standard_form.md`
 - [x] Add the set to the relevant table in `docs/src/manual/standard_form.md`

## Tests

 - [ ] Define a new `_set(::Type{S})` method in `src/Test/test_basic_constraint.jl`
       and add the name of the set to the list at the bottom of that files
 - [ ] If the set has any checks in its constructor, add tests to `test/sets.jl`

## MathOptFormat

 - [ ] Open an issue at `https://github.com/jump-dev/MathOptFormat` to add
       support for the new set {{ replace with link to the issue }} **I don't think we should add any set specialization of that set or at least not yet**

## Optional

 - [x] Implement `dual_set(::S)` and `dual_set_type(::Type{S})`
 - [x] Add new tests to the `Test` submodule exercising your new set
 - [ ] Add new bridges to convert your set into more commonly used sets
